#ifndef C2_DATA_H
#define C2_DATA_H

/* Data externs only; safe to include without changing call prototypes. */

/* Shared structs/macros (figure_list, city_map, ...). */
#include "c2_types.h"

/* ── Data externs ───────────────────────────────────── */

extern int D;
extern int LBM_HEADER1[];
extern int LBM_HEADER2[];
extern int LBM_PADDING;
extern int S_dig[];
extern int S_mdi[];
extern struct dpmi_real_block VesaInfo;
extern struct dpmi_real_block VesaModeInfo;
extern int absolute_ofset;
extern int accessed_hospitals_count;
extern int accessed_hospitals_pass_count;
extern int accessed_libraries_count;
extern int accessed_libraries_pass_count;
extern int account_construction_cost;
extern int account_pop_tax;
extern int account_operating_cost;
extern int account_ind_tax;
extern int account_total;
extern int account_tribute;
extern int act_start_pm_ptr;
extern int act_start_ptr;
extern int act_start_x;
extern int act_start_y;
extern int action_sound;
extern unsigned char active_tutorial_pages[];
extern int adjust_max;
extern int adjust_min;
extern int adjust_step;
extern int * adjust_var;
extern int admin_debar;
extern int age_count;
extern int allocable_memory;
extern unsigned char allow_padding;
extern int anti_ferret_count;
extern int anti_ferret_moves;
extern int anti_ferret_ptr;
extern int anti_ferret_running;
extern int anti_ferret_x;
extern int anti_ferret_y;
extern int aquaduct_tops[];
extern int aquaduct_tops2[];
extern int arena_count;
extern int arena_culture_count;
extern int arena_culture_pass_count;
extern int arena_pass_count;
extern int arena_top_count;
extern short army_a;
extern short army_b;
extern short army_no;
extern int army_wage_level;
extern short arrow_a;
extern short arrow_no;
extern int at_limit;
extern int attack_direction;
extern int attack_from_sea;
extern int attacking_region;
extern int auto_conquered;
extern int auto_conquered_months;
extern int av_imperial_gift_level;
extern int average_cohort_morale;
extern int average_cohort_readiness;
extern int average_ind_tax_asses;
extern int average_ind_tax_denariis;
extern int average_pop_tax_asses;
extern int average_pop_tax_denariis;
extern int average_rating;
extern int avl_memory;
extern int bad_mood;
extern int bank_ptr;
extern int barb_entry_count;
extern int barb_ptr;
extern int barb_x;
extern int barb_y;
extern int barbarian_name_count;
extern int barracks_count;
extern int barracks_pass_count;
extern int bat_ai_trig_count;
extern int bat_attack_rate;
extern int bat_attacker_clock;
extern int bat_control;
extern int bat_enemy_first_fan_unit;
extern int bat_enemy_left_flank_unit;
extern int bat_enemy_right_flank_unit;
extern int bat_enemy_second_fan_unit;
extern int bat_hi;
extern int bat_morale;
extern int bat_no;
extern int bat_no_of_units;
extern int bat_no_selected;
extern int bat_odds;
extern int bat_order;
extern int bat_side;
extern int bat_size;
extern int bat_spacing;
extern int bat_tribe;
extern int bat_which;
extern int bat_width;
extern int baths_count;
extern int baths_pass_count;
extern int battle2_ptr;
extern int battle_ai_count;
extern int battle_direction;
extern int battle_drag_on;
extern int battle_drag_start_x;
extern int battle_drag_start_y;
extern int battle_npc_retreat_count;
extern int battle_over_count;
extern int battle_pm_x;
extern int battle_pm_y;
extern int battle_scale;
extern int battle_setup_count;
extern int battle_state;
extern int battle_stats_control;
extern int battle_stats_men;
extern int battle_stats_morale;
extern int battle_stats_nof_units;
extern int battle_stats_start_men;
extern int battle_stats_type;
extern int battle_turbo;
extern int battle_turbo_count;
extern int battle_type;
extern int battle_victor;
extern int best_elastic_dirc;
extern int best_elastic_value;
extern char black_out_data[];
extern int blue_cycle_count;
extern unsigned char bow_images[];
extern unsigned char * building_data1;
extern unsigned char * building_data2;
extern unsigned char * building_data3;
extern unsigned char * building_data4;
extern int buildings_lv_effect[];
extern int business_build_type;
extern int business_count;
extern int business_pass_count;
extern char button_speed_profile[];
extern int button_time_flag;
extern char card_ids[];
extern int card_is;
extern int card_sub_type;
extern int cards_recognised;
extern int char_count;
extern unsigned char choice_count;
extern unsigned char choice_info;
extern int circus_count;
extern int circus_culture_count;
extern int circus_culture_pass_count;
extern int circus_maximus_count;
extern int circus_maximus_culture_count;
extern int circus_maximus_culture_pass_count;
extern int circus_maximus_pass_count;
extern int circus_pass_count;
extern short citizen_b;
extern short citizen_no;
extern short citizen_a;
extern signed char citizen_speed_off_road[];
extern signed char citizen_speed_on_road[];
extern int city_anim128;
extern int city_anim16;
extern int city_anim32;
extern int city_anim64;
extern int city_anim8;
extern int city_costs[];
extern int city_direction;
extern int city_flag_list[];
extern int city_icons_to_help[];
extern int city_jars_x_off[][4];
extern int city_jars_y_off[][4];
extern int city_level_good_supply[];
extern short city_mm_enties[];
extern char city_palette[];
extern int city_pm_x;
extern int city_pm_y;
extern int city_ptr;
extern unsigned char * city_qptr;
extern int city_rotation;
extern int city_tune_playing;
extern unsigned char city_tutorial_icons[];
extern int city_type_x_off[][4];
extern int city_type_y_off[][4];
extern int city_zoom_level;
extern int clock_ferret_count;
extern int clock_ferret_moves;
extern int clock_ferret_ptr;
extern int clock_ferret_running;
extern int clock_ferret_x;
extern int clock_ferret_y;
extern int cm_dptr;
extern int cm_sptr;
extern int cm_x;
extern int cm_y;
extern int cmu_count[];
extern int cnt128;
extern int cnt16;
extern int cnt2;
extern int cnt256;
extern int cnt32;
extern int cnt4;
extern int cnt64;
extern int cnt8;
extern int coast_count;
extern int codesize;
extern int cohort_drill_spacing[];
extern unsigned char cohort_in_action[];
extern int colosseum_count;
extern int colosseum_culture_count;
extern int colosseum_culture_pass_count;
extern int colosseum_pass_count;
extern int colosseum_top_count;
extern int com_h;
extern int com_w;
extern int com_x;
extern int com_y;
extern int completed_provinces;
extern unsigned char confirming;
extern int conscription_rate;
extern int conscription_to_revolt_data[];
extern unsigned char continue_tutorial_status;
extern short created_army_no;
extern short created_arrow_no;
extern short created_citizen_no;
extern short created_figure_no;
extern short created_unit_no;
extern int cscreen;
extern int culture_rating_pop_limit;
extern int current_construction_cost;
extern int current_gdp;
extern int current_no_of_irregulars;
extern int current_no_of_centuries;
extern int current_no_of_regulars;
extern int current_no_of_auxillaries;
extern int culture_rating;
extern int current_no_of_soldiers;
extern int current_no_of_specials;
extern int current_operating_cost;
extern unsigned char current_palette[];
extern int current_temple_tip;
extern int cursor_x;
extern int cursor_y;
extern int cycle_count;
extern unsigned char d_code[];
extern unsigned char d_len[];
extern int danger_flag_list[];
extern int danger_flag_map_mode;
extern int data_ptr;
extern unsigned char * db_buf[];
extern int db_buffer_size;
extern int db_handle;
extern int db_playing;
extern int db_recommended_buffer_size;
extern unsigned char debar_fade_click;
extern char debug_interupt;
extern unsigned char decision;
extern int demo_mode;
extern int denarii;
extern unsigned char develop_mode;
extern unsigned char diamond_ofsets_2x[];
extern unsigned char diamond_ofsets_3x[];
extern unsigned char diamond_ofsets_4x[];
extern int dig;
extern int dig_status;
extern int donation_level;
extern int dos_memory;
extern int drive_name;
extern int ds;
extern int dummy_sav;
extern int dx;
extern int dy;
extern int east_border_x;
extern int east_border_y;
extern int east_trader_brings;
extern int east_trader_count0;
extern int east_trader_count1;
extern int east_trader_is;
extern int education_debar;
extern int elastic_start_dirc;
extern char elephant_archer_images[];
extern int elephant_riders[];
extern int emergency_mood;
extern unsigned char empire[];
extern unsigned char empire_connections[4];
extern int empire_rating;
extern int empire_rating_pop_limit;
extern int empire_region_order[];
extern int empire_won[];
extern int employees;
extern int employment_pass_count;
extern int employment_rate;
extern int employment_running_count;
extern int employment_to_pop_growth_factor[];
extern short enemy_figure;
extern short enemy_army;
extern short enemy_citizen;
extern short enemy_unit;
extern int entertainment_debar;
extern int entertainment_level;
extern int estimate_construction_cost;
extern int estimate_pop_tax;
extern int estimate_operating_cost;
extern int estimate_ind_tax;
extern int estimate_total;
extern int estimate_tribute;
extern int evolve_clock;
extern int evolve_col;
extern int evolve_count;
extern int evolve_row;
extern int evolve_tick3;
extern int evolve_tick4;
extern int ex;
extern unsigned char exit_flag;
extern int exit_x_at;
extern int exit_y_at;
extern char extension[4];
extern int extra_auxillaries;
extern int extra_irregulars;
extern int extra_regulars;
extern int extra_specials;
extern int ey;
extern int fb_count;
extern int fb_current_char_length;
extern int fb_limit;
extern int fb_line_length;
extern int fb_max_char_length;
extern int fb_max_width_reached;
extern int fb_no_of_lines;
extern int ferret_energy;
extern int ferret_home;
extern int ferret_horiz_off;
extern unsigned char * ferret_map;
extern int ferret_map_hi;
extern int ferret_map_wi;
extern char ferret_run[];
extern int ferret_targ_ptr;
extern int ferret_targ_x;
extern int ferret_targ_y;
extern int ferret_run_length;
extern int ferret_vert_off;
extern unsigned char fig_at_edge;
extern unsigned char * figure10_data;
extern unsigned char * figure1_data;
extern unsigned char * figure2_data;
extern unsigned char * figure3_data;
extern unsigned char * figure4_data;
extern unsigned char * figure5_data;
extern unsigned char * figure6_data;
extern unsigned char * figure7_data;
extern unsigned char * figure8_data;
extern unsigned char * figure9_data;
extern short figure_a;
extern short figure_no;
extern unsigned char file_loaded_status;
extern int file_no;
extern int file_string;
extern char filename[];
extern int final_bribe;
extern int fire_pass_count;
extern int fire_cover;
extern int fire_accident;
extern int fire_rate;
extern int fire_running_count;
extern int fire_spread_count;
extern int fire_spread_direction;
extern int fire_spread_target;
extern signed char fire_zones[];
extern int first_back;
extern unsigned char first_choice;
extern int first_entry;
extern int first_front;
extern int first_help_page;
extern int first_rear;
extern unsigned char * fixt_data;
extern int flag_for_workhouse_request;
extern int flag_mode;
extern int flag_mode_decay_count;
extern unsigned char font1[];
extern unsigned char font2[];
extern int font_screen_limit;
extern int font_style;
extern unsigned char format_buffer[];
extern int forts_count;
extern int forts_pass_count;
extern unsigned char forum_dept;
extern unsigned char forum_dept_over;
extern unsigned char forum_gfxdat[];
extern int forum_repapering[];
extern int forum_viewed_army;
extern unsigned char fountain_gfxdat[];
extern int fountains_count;
extern int fountains_pass_count;
extern int free_memory;
extern int free_message_ptr;
extern unsigned char game_panels[];
extern int game_state;
extern int gamesource;
extern int gardens_culture_count;
extern int gardens_culture_pass_count;
extern unsigned char gen_refresh1;
extern unsigned char gen_refresh2;
extern unsigned char gen_refresh3;
extern char gen_refresh4;
extern unsigned short getbuf;
extern unsigned char getlen;
extern char gmn[];
extern int gmn_count;
extern int gmn_density;
extern int gmn_err_sptr;
extern int gmn_err_x;
extern int gmn_err_y;
extern int gmn_ew_count;
extern int gmn_flag;
extern int gmn_run;
extern int gmn_max_run;
extern int gmn_nesw_count;
extern int gmn_ns_count;
extern int gmn_nwse_count;
extern int gmn_polar_count;
extern int gmn_sptr;
extern int gmn_type;
extern int gmn_type_limit;
extern int gmn_types[];
extern int gmn_x;
extern int gmn_y;
extern int got_cursx;
extern int grammaticus_count;
extern int grammaticus_culture_count;
extern int grammaticus_culture_pass_count;
extern int grammaticus_pass_count;
extern int granularity;
extern int greyed_out;
extern unsigned char greying_data[256];
extern int gx;
extern int gy;
extern int had_clear_sound;
extern int health_debar;
extern int help_debar[];
extern short help_history[];
extern char help_palname[];
extern int help_redir_house_history[];
extern int help_redir_house_tips[];
extern int help_redir_temple_history[];
extern int help_redir_temple_tips[];
extern char highlight;
extern short highlight_goods_list[];
extern int history_end_ptr;
extern int history_entries;
extern int history_entry[];
extern int history_graph_length;
extern int history_graph_years[];
extern int history_start_ptr;
extern int hlite_bottom;
extern int hlite_centre_x;
extern int hlite_centre_y;
extern int hlite_left;
extern int hlite_off_ptr;
extern int hlite_off_x;
extern int hlite_off_y;
extern int hlite_right;
extern int hlite_squares;
extern int hlite_top;
extern unsigned char hold_hot_keys;
extern unsigned char hold_mouse_replace;
extern unsigned char horsebow_images[];
extern int hospital_cover;
extern int hospitals_count;
extern int hospitals_pass_count;
extern unsigned char hot_exit_flag;
extern unsigned char hot_key_out_off_build;
extern unsigned char * house_data;
extern unsigned char house_gfxdat[];
extern int houses_to_income[];
extern int houses_to_people[];
extern int housing_cheat;
extern short hunting_army;
extern int income_multiple;
extern int illegal_build;
extern int imperial_favour;
extern int players_denarii;
extern int imperial_req_amount;
extern int imperial_req_goods;
extern int imperial_request;
extern int imperial_review;
extern int imperial_send_amount;
extern int imperial_tax;
extern int in_census_mode;
extern int in_the_forum;
extern int icon_strip_toggle;
extern int ind_growth_factor;
extern int ind_growth_future;
extern int ind_income_pass_count;
extern int ind_tax_counts;
extern int ind_tax_last_count;
extern int ind_tax_rate;
extern int ind_tax_running_total;
extern int ind_tax_to_growth_data[];
extern int industry_build_ok;
extern int industry_build_on;
extern int industry_build_type;
extern int industry_debar;
extern int insert_count;
extern unsigned char insert_cursor;
extern int insert_place;
extern char insert_text[];
extern int insurrection_factor;
extern int insurrection_future;
extern unsigned short int_battle_header[];
extern unsigned short int_city_header[];
extern unsigned short int_region_header[];
extern unsigned char * internal_screen;
extern int ix;
extern int iy;
extern unsigned char key_ascii;
extern unsigned char key_ascii_was;
extern unsigned char key_code;
extern unsigned char key_ready;
extern int lacking_auxillaries;
extern int lacking_irregulars;
extern int lacking_regulars;
extern int lacking_specials;
extern unsigned char landfill[];
extern unsigned char landfill_pool[];
extern int large_forums_count;
extern int large_forums_pass_count;
extern int large_robbery_count;
extern int large_robbery_pass_count;
extern int large_temples_count;
extern int large_temples_culture_count;
extern int large_temples_culture_pass_count;
extern int large_temples_pass_count;
extern int last_adjusted_cohort;
extern int last_anti_ferret_dirc;
extern int last_army_route_point;
extern int last_battle_mood;
extern int last_city_flag;
extern int last_city_mood;
extern int last_clock_ferret_dirc;
extern int last_danger_flag;
extern unsigned char last_forum_dept;
extern int last_house_query_mode;
extern int last_icon_over;
extern int last_icon_used;
extern int last_imperial_tax_amount;
extern int last_imperial_tax_percent;
extern int last_prov_flag;
extern int last_tribute;
extern int last_tutorial_page;
extern int last_years_denarii;
extern int last_years_ind_tax;
extern int last_years_pop_tax;
extern int last_years_population;
extern unsigned char letter_table[];
extern unsigned char lf_tiles[];
extern int lib_para1;
extern int lib_para2;
extern int lib_para3;
extern int lib_para4[];
extern int lib_ret1;
extern int lib_ret2;
extern int lib_ret3;
extern int lib_ret4;
extern int libraries_count;
extern int libraries_pass_count;
extern int library_cover;
extern int linked_text_flag;
extern int local_time;
extern unsigned char logos[];
extern unsigned char losses_to_morale[];
extern int lv_debar;
extern int main_paras[10];
extern int map_actual_atom;
extern int map_actual_height;
extern int map_actual_width;
extern int map_direction;
extern char map_gfx_loaded;
extern int map_height_reduction;
extern unsigned char map_mode;
extern int map_width_reduction;
extern int marching_fx;
extern int market_count;
extern int market_pass_count;
extern short match_length;
extern short match_position;
extern int max_memory;
extern int mercs_in_army;
extern int max_population;
extern int mdi;
extern int mdi_status;
extern int med_robbery_count;
extern int med_robbery_pass_count;
extern int med_temples_count;
extern int med_temples_culture_count;
extern int med_temples_culture_pass_count;
extern int med_temples_pass_count;
extern int media_left_image;
extern char media_line_buffer[];
extern int media_right_image;
extern int media_voc;
extern int medium_forums_count;
extern int medium_forums_pass_count;
extern struct dpmi_mem_info memory;
extern int mercs_catagory;
extern int mercs_cost_per_50;
extern int mercs_from;
extern int max_mercs_allowed;
extern int mercs_missile;
extern int mercs_speed;
extern int mercs_tribe;
extern int mercs_type;
extern unsigned char mess_goto_map[];
extern int message_goto_ptr;
extern unsigned char mice[];
extern unsigned char misc[];
extern int month;
extern int months_since_last_city_attack;
extern int months_since_last_horde;
extern int months_since_last_raider;
extern int months_since_last_revolt;
extern int months_since_last_war;
extern int months_to_game_over;
extern char mouse_background[];
extern int mouse_installed;
extern unsigned char mouse_left_button;
extern unsigned char mouse_left_click;
extern unsigned char mouse_left_preclick;
extern int mouse_movement;
extern int mouse_ptr[];
extern unsigned char mouse_right_button;
extern unsigned char mouse_right_click;
extern unsigned char mouse_right_preclick;
extern int mouse_styles[];
extern int mouse_was_pressed;
extern int needed_no_of_regulars;
extern int mouse_y;
extern int moving_tribute;
extern int ms;
extern unsigned char mse_button;
extern short mse_x;
extern short mse_y;
extern int multiples[];
extern char need_glf;
extern int mouse_x;
extern int needed_no_of_centuries;
extern int needed_no_of_irregulars;
extern int needed_no_of_auxillaries;
extern int needed_no_of_soldiers;
extern int needed_no_of_specials;
extern char negative_buffer[];
extern int new_structure_is;
extern int next_cohort_free;
extern int next_sample;
extern int next_sequence;
extern int no_of_armies;
extern int no_of_army_buttons;
extern int no_of_arrows;
extern int no_of_barbarians;
extern int no_of_border_towns;
extern int no_of_census_passes;
extern int no_of_citizens;
extern int no_of_city_flags;
extern int no_of_cohorts_in_action;
extern int no_of_connected_towns;
extern int no_of_danger_flags;
extern int no_of_empire_connections;
extern int no_of_entries;
extern int no_of_farms;
extern int no_of_figures;
extern int no_of_mines;
extern int no_of_ports;
extern int no_of_prov_flags;
extern int no_of_quarrys;
extern int no_of_rioters;
extern int no_of_shipyards;
extern int no_of_towns;
extern int no_of_trading_posts;
extern int no_of_units;
extern int no_of_villages;
extern int no_of_workcamps;
extern int no_of_warehouses;
extern int nomansland_ptr;
extern int nof_hot_spots;
extern int nof_query_buttons;
extern int north_border_x;
extern int north_border_y;
extern int north_trader_brings;
extern int north_trader_count0;
extern int north_trader_count1;
extern int north_trader_is;
extern int odd_battle_tune;
extern int odium_count;
extern int odium_culture_count;
extern int odium_culture_pass_count;
extern int odium_pass_count;
extern int ofset_x;
extern int ofset_y;
extern char old3c5_4;
extern char old3cf_5;
extern char old3cf_6;
extern char old3d5_14;
extern char old3d5_17;
extern char * old_key_buffer;
extern char old_map_mode;
extern int old_mouse_drops_x;
extern int old_mouse_drops_y;
extern unsigned char old_mouse_lb;
extern unsigned char old_mouse_rb;
extern int old_mouse_x;
extern int old_mouse_y;
extern int old_pm_over;
extern unsigned char scrolling;
extern int old_sprite_x;
extern int old_sprite_y;
extern char old_zoom_level;
extern int oscreen;
extern int our_battle_auxs;
extern short our_battle_army;
extern int our_battle_horse;
extern int our_battle_irregs;
extern int our_battle_men;
extern int our_battle_morale;
extern int our_battle_regs;
extern int our_battle_routs;
extern int our_battle_specials;
extern int our_battle_stance;
extern int our_battle_start_men;
extern int our_battle_units;
extern int out1;
extern int out2;
extern int out3;
extern int out4;
extern int out5;
extern int out6;
extern int out7;
extern int out8;
extern char ov2_map_mode;
extern unsigned char ov_map_mode;
extern int over_an_army;
extern int over_ptr;
extern int over_x;
extern int over_y;
extern int overlay0_empty_mode;
extern int overlays_on;
extern unsigned char p_code[];
extern unsigned char p_len[];
extern unsigned char padding_off;
extern int para1;
extern int para2;
extern int particles_built;
extern int particles_cleared;
extern char path_name[];
extern int pax_romanum;
extern int peace_rating_pop_limit;
extern unsigned char * people_data;
extern int peace_rating;
extern int placing_cost;
extern int placing_flags;
extern int placing_type;
extern int plague_accident;
extern int plague_offs[];
extern int plague_pass_count;
extern int plague_running_count;
extern int plague_spread_count;
extern int player_rank;
extern int plague_spread_direction;
extern int plague_spread_target;
extern int imperial_gift_level;
extern int players_salary;
extern int plaza_culture_count;
extern int plaza_culture_pass_count;
extern int pm_build_shape;
extern int pm_diamond_half_height;
extern int pm_diamond_half_width;
extern int pm_screen_y_start;
extern int pm_diamond_width;
extern int pm_over;
extern int pm_over_cm_ptr;
extern int pm_over_x;
extern int pm_over_y;
extern int pm_screen_height;
extern int pm_screen_width;
extern int pm_screen_x_end;
extern int pm_screen_x_start;
extern int pm_screen_y_end;
extern int pm_diamond_height;
extern int pm_shown_ptr;
extern int pm_shown_x;
extern int pm_shown_y;
extern int pm_x;
extern int pm_x_coord;
extern int pm_x_edge;
extern int pm_y;
extern int pm_y_clip;
extern int pm_y_coord;
extern int pm_y_edge;
extern int pmp_iptr;
extern int pmp_length;
extern int pmp_mem_needed;
extern int pmp_optr;
extern unsigned char pointer_mode;
extern int pompous_conquests[];
extern int pop_growth_extra;
extern int pop_growth_extra_count;
extern int pop_growth_factor;
extern int pop_growth_future;
extern int pop_income_pass_count;
extern int pop_tax_counts;
extern int pop_tax_last_count;
extern int pop_tax_rate;
extern int pop_tax_running_total;
extern int pop_tax_to_growth_data[];
extern int population;
extern int population_pass_count;
extern int population_running_count;
extern char positive_buffer[];
extern unsigned char pre_loaded_status;
extern int prefectures_count;
extern int prefectures_pass_count;
extern int promotion_cheat;
extern char promotions_to_win_game[];
extern int prosperity_rating;
extern int prosperity_rating_pop_limit;
extern int prov_flag_list[];
extern int prov_rotation;
extern int prov_zoom_level;
extern int province_difficulty;
extern int province_is;
extern int provinces_on_offer;
extern int provincial_difficulty[];
extern unsigned char put_a_message;
extern unsigned short putbuf;
extern unsigned char putlen;
extern unsigned char q_admin;
extern unsigned char q_aqua;
extern unsigned char q_barracks;
extern unsigned char q_baths;
extern unsigned char q_business;
extern unsigned char q_business_low;
extern unsigned char q_business_vlow;
extern unsigned char q_circus;
extern unsigned char q_colosseum;
extern unsigned char q_cover1;
extern unsigned char q_cover2;
extern unsigned char q_entertainment;
extern unsigned char q_flag;
extern unsigned char q_gate;
extern unsigned char q_gfx;
extern unsigned char q_goods;
extern unsigned char q_grammaticus;
extern unsigned char q_had_goods;
extern int q_hospital_access;
extern unsigned char q_ind_market;
extern unsigned char q_ind_output;
extern unsigned char q_ind_pop;
extern int q_local;
extern signed char q_lv;
extern unsigned char q_market;
extern unsigned char q_near_market;
extern int q_no_of_people;
extern unsigned char q_occa;
extern unsigned char q_outside;
extern unsigned char q_patrol;
extern unsigned char q_people_list[];
extern int q_pop_level;
extern unsigned char q_prefecture;
extern int q_ptr;
extern unsigned char q_range1;
extern unsigned char q_range3;
extern unsigned char q_rhetor;
extern unsigned char q_road;
extern unsigned char q_road_access;
extern unsigned char q_security;
extern unsigned char q_shell;
extern int rand8;
extern unsigned char q_sub_aqua;
extern int q_supplies;
extern unsigned char q_supply;
extern unsigned char q_theatre;
extern unsigned char q_type;
extern unsigned char q_wall;
extern unsigned char q_wh_level;
extern int q_workhouse;
extern int queried_person;
extern int query_mode;
extern int query_panel_reduction;
extern int rand128;
extern int rand32000;
extern unsigned int randseed;
extern unsigned char redraw_icons;
extern unsigned char redraw_topline;
extern int ref_ptr;
extern int ref_x;
extern int ref_y;
extern int refresh_count;
extern int refused_promotion;
extern char reg_aquaduct_gfxdat[];
extern int reg_city_ptr;
extern int reg_city_x;
extern int reg_city_y;
extern int reg_placing_flags;
extern int reg_placing_type;
extern int reg_type_x_off[][4];
extern int reg_type_y_off[][4];
extern char reg_wall_gfxdat[];
extern int region_accident;
extern int region_costs[];
extern int region_direction;
extern int region_icons_to_help[];
extern char region_mm_enties[];
extern int region_over;
extern char region_palette[];
extern int region_pass_count;
extern int region_pm_x;
extern int region_pm_y;
extern int region_rate;
extern int region_running_count;
extern unsigned char region_tutorial_icons[];
extern int religion_level;
extern unsigned char restart_flag;
extern int retreat_flag;
extern int return_map_mode;
extern int return_zoom_level;
extern int revolt_accident;
extern int revolt_size;
extern int rhetor_count;
extern int rhetor_culture_count;
extern int rhetor_culture_pass_count;
extern int rhetor_pass_count;
extern int road_accident;
extern int road_cover;
extern int road_pass_count;
extern int road_rate;
extern int road_running_count;
extern int robbery_count;
extern int rolling_profit;
extern int roman_back_edge;
extern int roman_front_edge;
extern int roman_left_edge;
extern int roman_name_count;
extern int roman_right_edge;
extern unsigned char rotated2_bank0[];
extern unsigned char rotated2_bank1[];
extern unsigned char rotated2_bank2[];
extern unsigned char rotated2_bank3[];
extern unsigned char rotated_bank0[];
extern unsigned char rotated_bank1[];
extern unsigned char rotated_bank2[];
extern unsigned char rotated_bank3[];
extern unsigned char rotated_bank4[];
extern int samples_running;
extern unsigned char sb_cm_undo_flushed;
extern unsigned char sb_rm_undo_flushed;
extern int scat128;
extern int scat32000;
extern unsigned int scatseed;
extern unsigned char * scratch_buffer;
extern int scratch_buffer_size;
extern unsigned char screen_mode;
extern char screen_refresh_flag;
extern int screen_size;
extern int screen_width;
extern int scroll_amount;
extern unsigned char old_scrolling;
extern int security_debar;
extern int select_cost_flag;
extern int select_count;
extern int screen_height;
extern int select_height;
extern int select_width;
extern int selected_icon_no;
extern int selected_icon_text;
extern short selection_goods_list[];
extern int selection_is;
extern int sequences_running;
extern int shell_last_value;
extern int shell_push_direction;
extern int shell_wall_flag;
extern int show_message_ptr;
extern char size2_from_type[];
extern char size_from_type[];
extern int skill_to_city_attacks[];
extern int skill_to_denarii_reduction[5];
extern int skill_to_imperial_request[];
extern int skill_to_starting_denarii[];
extern int slave_population_change;
extern int slave_population_estimate;
extern int slave_population_final_estimate;
extern int slave_random;
extern int slave_warning;
extern int slave_welfare_bill;
extern int slaves;
extern int slider_total;
extern int slidper_on;
extern unsigned char sling_images[];
extern char * smack_filename;
extern int smack_frame;
extern int smack_from_cd;
extern int smacker_on;
extern int smacker_open;
extern char smacks[40][14];
extern int small_forums_count;
extern int small_forums_pass_count;
extern int small_robbery_count;
extern int small_robbery_pass_count;
extern int small_temples_count;
extern int small_temples_culture_count;
extern int small_temples_culture_pass_count;
extern int small_temples_pass_count;
extern int smk_height;
extern int smk_ref_hi;
extern int smk_ref_wi;
extern int smksumy[];
extern int south_border_x;
extern int south_border_y;
extern int south_trader_brings;
extern int south_trader_count0;
extern int south_trader_count1;
extern int south_trader_is;
extern int sprite_height;
extern int sprite2_image_no;
extern int sprite2_start;
extern int sprite2_width;
extern int sprite2_height;
extern int sprite3_image_no;
extern int sprite3_start;
extern int sprite3_width;
extern int sprite_bank;
extern int sprite_bank_ofset;
extern int sprite_base_x;
extern int sprite_base_y;
extern int sprite_colour;
extern int sprite_error;
extern int sprite_hat_start;
extern int sprite3_height;
extern int sprite_image_no;
extern int sprite_next_bank_count;
extern int sprite_size;
extern int sprite_start;
extern int sprite_width;
extern int sprite_x;
extern int sprite_x_off;
extern int sprite_y;
extern int sprite_y_off;
extern int sslot;
extern int start_sptr;
extern int start_x_pos;
extern int start_y_pos;
extern int start_year;
extern int starting_denarii;
extern int steves_security_false1[];
extern int steves_security_false2[];
extern int steves_security_real[];
extern int stolen_denarii;
extern signed char stone_random_count;
extern unsigned char stone_random_data[];
extern unsigned char stopped_scrolling;
extern int structure_pass_count;
extern int structure_running_count;
extern int supplied_baths_count;
extern int supplied_baths_pass_count;
extern int supplied_fountains_count;
extern int supplied_fountains_pass_count;
extern unsigned char svga_refresh_table[];
extern unsigned char system_panel[];
extern int target_unit_debar;
extern int tax_rates[];
extern int tax_to_revolt_data[];
extern int tax_triggers[];
extern unsigned char tb_occ_a_flag;
extern unsigned char tb_occ_b_flag;
extern unsigned char tb_prev_flag;
extern int tb_ptr;
extern unsigned char tb_road_flag;
extern int tb_x;
extern int tb_y;
extern short temp_arrow;
extern short temp_army;
extern short temp_citizen;
extern int temp_demand_count[];
extern short temp_figure;
extern char temp_palette[];
extern int temples_count;
extern short temp_unit;
extern unsigned char test_mode1;
extern unsigned char test_mode2;
extern unsigned char test_mode3;
extern unsigned char test_mode4;
extern int test_result1;
extern int test_result2;
extern int test_result3;
extern int test_result4;
extern int test_value1a;
extern int test_value1b;
extern int test_value1c;
extern int test_value1d;
extern int test_value2a;
extern int test_value2b;
extern int test_value2c;
extern int test_value2d;
extern int test_value3a;
extern int test_value3b;
extern int test_value3c;
extern int test_value3d;
extern int test_value4a;
extern int test_value4b;
extern int test_value4c;
extern int test_value4d;
extern char text_buffer[];
extern char * text_pointer;
extern int textsize;
extern int theatre_count;
extern int theatre_culture_count;
extern int theatre_culture_pass_count;
extern int theatre_pass_count;
extern int their_battle_auxs;
extern int their_battle_horse;
extern int their_battle_irregs;
extern int their_battle_men;
extern int their_battle_morale;
extern int their_battle_regs;
extern int their_battle_routs;
extern int their_battle_specials;
extern int their_battle_stance;
extern int their_battle_start_men;
extern int their_battle_units;
extern int this_help_action;
extern int this_help_page;
extern int this_letter;
extern int this_route_number;
extern short their_battle_army;
extern int this_spot;
extern int this_years_denarii;
extern int this_years_ind_tax;
extern int this_years_pop_tax;
extern int this_years_population;
extern int threat_mood;
extern int time_is;
extern int top_lv;
extern int top_lv_ptr;
extern int top_lv_spot;
extern int top_lv_x;
extern int top_lv_y;
extern unsigned char * tops_data;
extern int total_amount_of_bribes;
extern int total_build_cost;
extern int total_imperial_taxes;
extern int total_no_of_auxillaries;
extern int total_no_of_bribes;
extern int total_no_of_centuries;
extern int total_no_of_cohorts;
extern int total_no_of_irregulars;
extern int total_no_of_regulars;
extern int total_no_of_soldiers;
extern short tracking_army;
extern unsigned char tribe_to_standard[];
extern unsigned char tribe_to_troops[];
extern char tribe_type[];
extern int tribute;
extern int tribute_adjust[];
extern int tune1;
extern int total_no_of_specials;
extern int tune2;
extern int tune_branch;
extern int tune_branch_count;
extern unsigned char tune_buffer[];
extern int tune_mood;
extern int tune_mood_hold;
extern int turbo_mode;
extern int tutorial_correct;
extern int tutorial_correct_timer;
extern int tutorial_level;
extern int tutorial_mode;
extern int tutorial_page;
extern int tutorial_timer;
extern short unit_a;
extern short unit_no;
extern int utility_level;
extern int unrest_debar;
extern int unrest_random_count;
extern int unrest_random_data[];
extern int update_icon;
extern unsigned char update_landfill;
extern unsigned char update_map;
extern int update_ov_bar;
extern int used_memory;
extern int vgawintab[];
extern int vid_bank_tech;
extern int vid_error;
extern int vid_memory;
extern char vid_new_val;
extern int vid_no_of_banks;
extern char vid_old_val;
extern int vid_tech;
extern char vid_val;
extern unsigned char w_dirc;
extern int wall_accident;
extern int wall_cover;
extern int wall_rate;
extern int warned_city_size;
extern int warned_new_struct;
extern char warned_of_cutbacks;
extern unsigned char warned_of_emperor;
extern unsigned char warned_of_emperor_reply_level;
extern unsigned char warned_of_emperor_reply_month;
extern char warned_of_fire;
extern char warned_of_free4;
extern char warned_of_free5;
extern int warned_of_not_build;
extern unsigned char warned_of_robbery;
extern int water_cover;
extern int water_debar;
extern int water_running_count;
extern int water_trouble_rate;
extern unsigned char web_dirc;
extern unsigned char web_directions;
extern int web_first_actual_node;
extern unsigned char web_from;
extern int web_node;
extern int web_node_count;
extern int web_nof_dircs;
extern int web_out_of_the_walls;
extern int web_ptr;
extern int web_start_x;
extern int web_start_y;
extern int web_total_length;
extern int web_x;
extern int web_y;
extern int week;
extern int west_border_x;
extern int west_border_y;
extern int west_trader_brings;
extern int west_trader_count0;
extern int west_trader_count1;
extern int west_trader_is;
extern signed char wf_battle_dircs[];
extern int which_unit;
extern int x;
extern int x1;
extern int x_bit;
extern int x_end;
extern int x_is;
extern int x_length;
extern int x_ofset;
extern int x_start;
extern int x_wrap;
extern unsigned char xclipped;
extern int xleft_back;
extern int xleft_front;
extern int xleft_rear;
extern int xpos;
extern int xright_back;
extern int xright_front;
extern int xright_rear;
extern int y;
extern int y_bit;
extern int y_end;
extern int y_length;
extern int y_start;
extern int yback;
extern unsigned char yclipped;
extern int year;
extern int years_elapsed;
extern int years_elapsed_in_region;
extern int yfront;
extern int ypos;
extern int yrear;
extern int z_ptr;
extern int z_x;
extern int z_y;
extern int zone_x;
extern int zone_y;
extern unsigned char zoom_in_decay_count;
extern unsigned char zoom_level;

#endif /* C2_DATA_H */
