#ifndef C2_VARS_H
#define C2_VARS_H

/*
 * Shared-variable declarations in recovered Watcom symbol-handle page order.
 * PS BSS ordering proves the 33 page boundaries.  Pages appear here in source
 * order (oldest to newest); Watcom emits them in the reverse order shown by
 * the binary.  Equal-hash declarations are reversed within a page.
 */

/* Symbol page 0 (PS emission page 32). */
extern int pseudo_map[][81];
extern unsigned char landfill_pool[];
extern struct region_cell region_map[];
extern struct battle_cell battle_map[];
extern struct city_cell city_map[];

/* Symbol page 1 (PS emission page 31). */
extern int ferret_run_length;
extern int region_over;
extern struct army_route_rec army_routes[];
extern signed char fire_zones[];
extern struct figure_rec figure_list[];
extern int empire_won[];
extern short created_citizen_no;
extern short temp_citizen;
extern short citizen_no;
extern short created_figure_no;
extern short created_arrow_no;
extern short created_army_no;
extern short temp_army;
extern short army_no;
extern unsigned char warned_of_emperor_reply_level;
extern char warned_of_free4;
extern char warned_of_free5;
extern char warned_of_fire;
extern unsigned char warned_of_robbery;
extern unsigned char warned_of_emperor_reply_month;
extern unsigned char put_a_message;
extern unsigned char warned_of_emperor;
extern char warned_of_cutbacks;
extern struct byte_delta_rec gmn_ofsets[];
extern int steves_security_real[];

/* Symbol page 2 (PS emission page 30). */
extern int battle_over_count;
extern int battle_scale;
extern int bat_tribe;
extern int battle_ai_count;
extern int our_battle_men;
extern int battle_victor;
extern int battle_state;
extern int battle_setup_count;
extern struct msg_slot message_list[];
extern char region_palette[];
extern char city_palette[];
extern short figure_no;
extern char old_zoom_level;
extern unsigned char old_scrolling;
extern unsigned char sb_rm_undo_flushed;
extern unsigned char sb_cm_undo_flushed;
extern unsigned char update_landfill;
extern unsigned char redraw_icons;
extern unsigned char gen_refresh1;
extern unsigned char gen_refresh3;
extern unsigned char gen_refresh2;
extern char gen_refresh4;
extern unsigned char stopped_scrolling;
extern char old_map_mode;
extern unsigned char redraw_topline;

/* Symbol page 3 (PS emission page 29). */
extern int our_battle_specials;
extern int our_battle_units;
extern int battle_stats_morale;
extern int our_battle_routs;
extern int their_battle_stance;
extern int their_battle_men;
extern int their_battle_start_men;
extern int our_battle_start_men;
extern int our_battle_morale;
extern int battle_stats_nof_units;
extern int battle_stats_type;
extern int retreat_flag;
extern int battle_stats_men;
extern int their_battle_morale;
extern int our_battle_horse;
extern int their_battle_routs;
extern int our_battle_stance;
extern int their_battle_specials;
extern int our_battle_auxs;
extern int battle_stats_control;
extern int our_battle_irregs;
extern int our_battle_regs;
extern int battle_npc_retreat_count;
extern int their_battle_units;
extern int battle_stats_start_men;

/* Symbol page 4 (PS emission page 28). */
extern int roman_right_edge;
extern int mercs_in_army;
extern int battle2_ptr;
extern int mercs_tribe;
extern int battle_drag_on;
extern int mercs_cost_per_50;
extern int max_mercs_allowed;
extern int roman_left_edge;
extern int their_battle_irregs;
extern int mercs_missile;
extern int target_unit_debar;
extern int return_map_mode;
extern int mercs_from;
extern int mercs_type;
extern int roman_front_edge;
extern int battle_turbo;
extern int their_battle_auxs;
extern int battle_turbo_count;
extern int roman_back_edge;
extern int return_zoom_level;
extern int mercs_speed;
extern int mercs_catagory;
extern int battle_type;
extern int their_battle_regs;
extern int their_battle_horse;

/* Symbol page 5 (PS emission page 27). */
extern int hlite_off_y;
extern int hlite_off_x;
extern int blue_cycle_count;
extern int hlite_squares;
extern int bat_enemy_right_flank_unit;
extern int bat_enemy_second_fan_unit;
extern int emergency_mood;
extern int hlite_left;
extern int hlite_centre_y;
extern int hlite_centre_x;
extern int nomansland_ptr;
extern int hlite_right;
extern int hlite_top;
extern int battle_drag_start_y;
extern int battle_drag_start_x;
extern int next_cohort_free;
extern int no_of_cohorts_in_action;
extern int bat_enemy_first_fan_unit;
extern int hlite_off_ptr;
extern int hlite_bottom;
extern int bat_enemy_left_flank_unit;
extern int threat_mood;
extern int danger_flag_list[];
extern int city_flag_list[];
extern int prov_flag_list[];

/* Symbol page 6 (PS emission page 26). */
extern int last_city_mood;
extern int bad_mood;
extern int tune_mood_hold;
extern int new_structure_is;
extern int city_tune_playing;
extern int tune_branch;
extern int message_goto_ptr;
extern int warned_of_not_build;
extern int last_battle_mood;
extern int tune_branch_count;
extern int free_message_ptr;
extern int show_message_ptr;
extern int tune_mood;
extern int marching_fx;
extern int odd_battle_tune;
extern struct slave_req slave_requirements[];
extern short created_unit_no;
extern short unit_no;
extern short arrow_no;
extern short temp_figure;
extern unsigned char zoom_level;
extern unsigned char scrolling;
extern unsigned char map_mode;
extern unsigned char update_map;
extern unsigned char zoom_in_decay_count;

/* Symbol page 7 (PS emission page 25). */
extern int demo_mode;
extern int update_icon;
extern int warned_new_struct;
extern int tutorial_page;
extern int battle_direction;
extern int city_direction;
extern int region_direction;
extern int final_bribe;
extern int slave_warning;
extern int tutorial_mode;
extern int in_census_mode;
extern int warned_city_size;
extern int gmn_types[];
extern char gmn[];
extern struct province_industry province_industries[];
extern struct industry_rec     industry[];
extern struct citizen_rec citizen_list[];
extern struct unit_rec unit_list[];
extern unsigned char empire[];
extern char ferret_run[];
extern struct army_rec army_list[];
extern short arrow_a;
extern struct arrow_rec arrow_list[];
extern unsigned char w_dirc;
extern unsigned char fig_at_edge;

/* Symbol page 8 (PS emission page 24). */
extern int map_direction;
extern int overlays_on;
extern int map_height_reduction;
extern int map_actual_atom;
extern int city_rotation;
extern int prov_zoom_level;
extern int start_y_pos;
extern int city_ptr;
extern int map_actual_width;
extern int cm_dptr;
extern int start_x_pos;
extern int cm_sptr;
extern int map_width_reduction;
extern int prov_rotation;
extern unsigned char * city_qptr;
extern int city_zoom_level;
extern int map_actual_height;
extern int scroll_amount;
extern int in_the_forum;
extern int start_sptr;
extern struct help_hotspot help_page_hot_spots[];
extern short help_history[];
extern unsigned char q_people_list[];
extern unsigned char cohort_in_action[];
extern short citizen_a;

/* Symbol page 9 (PS emission page 23). */
extern int pm_screen_x_end;
extern int pm_screen_width;
extern int pm_build_shape;
extern int pm_y_clip;
extern int pm_screen_y_start;
extern int pm_screen_x_start;
extern int pm_shown_y;
extern int pm_shown_x;
extern int pm_y_edge;
extern int pm_y;
extern int pm_x;
extern int cm_x;
extern int cm_y;
extern int pm_x_coord;
extern int pm_y_coord;
extern int pm_x_edge;
extern int pm_diamond_width;
extern int pm_diamond_half_width;
extern int pm_screen_height;
extern int pm_diamond_height;
extern int pm_shown_ptr;
extern int pm_over_y;
extern int pm_over_x;
extern int pm_diamond_half_height;
extern int pm_screen_y_end;

/* Symbol page 10 (PS emission page 22). */
extern int no_of_city_flags;
extern int last_danger_flag;
extern int flag_mode;
extern int danger_flag_map_mode;
extern int pm_over_cm_ptr;
extern int no_of_danger_flags;
extern int last_city_flag;
extern int last_prov_flag;
extern int flag_mode_decay_count;
extern int old_pm_over;
extern int city_pm_y;
extern int city_pm_x;
extern int com_h;
extern int com_w;
extern int com_x;
extern int com_y;
extern int pm_over;
extern int no_of_prov_flags;
extern int battle_pm_y;
extern int battle_pm_x;
extern int region_pm_x;
extern int region_pm_y;
extern unsigned short int_city_header[];
extern unsigned short int_region_header[];
extern unsigned char misc[];

/* Symbol page 11 (PS emission page 21). */
extern int months_since_last_war;
extern int insurrection_future;
extern int elastic_start_dirc;
extern int pop_growth_factor;
extern int over_y;
extern int over_x;
extern int ind_growth_future;
extern int action_sound;
extern int best_elastic_value;
extern int over_ptr;
extern int insurrection_factor;
extern int last_army_route_point;
extern int pop_growth_extra_count;
extern int act_start_ptr;
extern int act_start_x;
extern int act_start_y;
extern int ind_growth_factor;
extern int had_clear_sound;
extern int pop_growth_extra;
extern int pop_growth_future;
extern int this_route_number;
extern int best_elastic_dirc;
extern int act_start_pm_ptr;
extern short enemy_citizen;
extern short citizen_b;

/* Symbol page 12 (PS emission page 20). */
extern int slaves;
extern int months_to_game_over;
extern int months_since_last_revolt;
extern int months_since_last_city_attack;
extern int week;
extern int pop_tax_rate;
extern int employment_rate;
extern int slave_population_change;
extern int month;
extern int employees;
extern int months_since_last_horde;
extern int max_population;
extern int slave_welfare_bill;
extern int years_elapsed;
extern int year;
extern int game_state;
extern int ind_tax_rate;
extern int denarii;
extern int population;
extern int start_year;
extern int months_since_last_raider;
extern int slave_population_final_estimate;
extern int years_elapsed_in_region;
extern int slave_population_estimate;
extern unsigned char landfill[];

/* Symbol page 13 (PS emission page 19). */
extern int players_denarii;
extern int imperial_req_goods;
extern int last_imperial_tax_percent;
extern int estimate_ind_tax;
extern int stolen_denarii;
extern int donation_level;
extern int estimate_total;
extern int last_imperial_tax_amount;
extern int total_imperial_taxes;
extern int estimate_operating_cost;
extern int current_construction_cost;
extern int account_operating_cost;
extern int account_ind_tax;
extern int imperial_tax;
extern int imperial_review;
extern int estimate_construction_cost;
extern int estimate_pop_tax;
extern int players_salary;
extern int imperial_favour;
extern int slave_random;
extern int account_construction_cost;
extern int imperial_request;
extern int account_pop_tax;
extern int current_operating_cost;
extern int account_total;

/* Symbol page 14 (PS emission page 18). */
extern int average_ind_tax_asses;
extern int last_tribute;
extern int moving_tribute;
extern int last_years_denarii;
extern int average_ind_tax_denariis;
extern int this_years_pop_tax;
extern int estimate_tribute;
extern int average_pop_tax_denariis;
extern int imperial_send_amount;
extern int last_years_ind_tax;
extern int forum_viewed_army;
extern int this_years_population;
extern int average_pop_tax_asses;
extern int tribute;
extern int income_multiple;
extern int total_amount_of_bribes;
extern int last_years_pop_tax;
extern int total_no_of_bribes;
extern int imperial_gift_level;
extern int last_years_population;
extern int imperial_req_amount;
extern int av_imperial_gift_level;
extern int this_years_denarii;
extern int account_tribute;
extern int this_years_ind_tax;

/* Symbol page 15 (PS emission page 17). */
extern int current_no_of_auxillaries;
extern int army_wage_level;
extern int total_no_of_soldiers;
extern int total_no_of_irregulars;
extern int current_no_of_regulars;
extern int current_no_of_soldiers;
extern int needed_no_of_centuries;
extern int needed_no_of_auxillaries;
extern int conscription_rate;
extern int current_no_of_irregulars;
extern int needed_no_of_soldiers;
extern int needed_no_of_regulars;
extern int total_no_of_centuries;
extern int extra_irregulars;
extern int lacking_auxillaries;
extern int extra_auxillaries;
extern int total_no_of_regulars;
extern int total_no_of_auxillaries;
extern int total_no_of_cohorts;
extern int no_of_army_buttons;
extern int current_no_of_centuries;
extern int needed_no_of_irregulars;
extern int lacking_regulars;
extern int extra_regulars;
extern int lacking_irregulars;

/* Symbol page 16 (PS emission page 16). */
extern int average_cohort_morale;
extern int current_no_of_specials;
extern int lacking_specials;
extern int pop_tax_counts;
extern int population_running_count;
extern int pop_income_pass_count;
extern int road_pass_count;
extern int ind_tax_counts;
extern int no_of_census_passes;
extern int population_pass_count;
extern int plague_pass_count;
extern int ind_tax_last_count;
extern int ind_tax_running_total;
extern int last_adjusted_cohort;
extern int employment_pass_count;
extern int extra_specials;
extern int pop_tax_last_count;
extern int fire_pass_count;
extern int structure_pass_count;
extern int pop_tax_running_total;
extern int needed_no_of_specials;
extern int total_no_of_specials;
extern int employment_running_count;
extern int ind_income_pass_count;
extern int average_cohort_readiness;

/* Symbol page 17 (PS emission page 15). */
extern int fountains_count;
extern int fountains_pass_count;
extern int forts_count;
extern int large_forums_pass_count;
extern int supplied_baths_count;
extern int barracks_pass_count;
extern int prefectures_count;
extern int supplied_fountains_count;
extern int supplied_fountains_pass_count;
extern int medium_forums_pass_count;
extern int large_forums_count;
extern int supplied_baths_pass_count;
extern int small_forums_count;
extern int structure_running_count;
extern int baths_count;
extern int road_running_count;
extern int fire_running_count;
extern int plague_running_count;
extern int baths_pass_count;
extern int prefectures_pass_count;
extern int medium_forums_count;
extern int forts_pass_count;
extern int water_running_count;
extern int barracks_count;
extern int small_forums_pass_count;

/* Symbol page 18 (PS emission page 14). */
extern int med_temples_culture_count;
extern int med_robbery_pass_count;
extern int med_temples_culture_pass_count;
extern int small_temples_culture_pass_count;
extern int libraries_count;
extern int large_robbery_count;
extern int med_robbery_count;
extern int large_temples_pass_count;
extern int hospitals_count;
extern int libraries_pass_count;
extern int small_robbery_pass_count;
extern int large_robbery_pass_count;
extern int large_temples_culture_pass_count;
extern int med_temples_pass_count;
extern int small_temples_culture_count;
extern int large_temples_culture_count;
extern int small_temples_count;
extern int accessed_hospitals_count;
extern int small_temples_pass_count;
extern int accessed_hospitals_pass_count;
extern int small_robbery_count;
extern int med_temples_count;
extern int hospitals_pass_count;
extern int accessed_libraries_pass_count;
extern int large_temples_count;

/* Symbol page 19 (PS emission page 13). */
extern int accessed_libraries_count;
extern int rhetor_pass_count;
extern int grammaticus_culture_pass_count;
extern int arena_count;
extern int theatre_pass_count;
extern int odium_pass_count;
extern int circus_maximus_pass_count;
extern int colosseum_pass_count;
extern int grammaticus_count;
extern int circus_maximus_count;
extern int grammaticus_pass_count;
extern int grammaticus_culture_count;
extern int odium_count;
extern int odium_culture_count;
extern int arena_pass_count;
extern int circus_pass_count;
extern int theatre_culture_pass_count;
extern int rhetor_culture_count;
extern int theatre_count;
extern int theatre_culture_count;
extern int odium_culture_pass_count;
extern int circus_count;
extern int colosseum_count;
extern int rhetor_culture_pass_count;
extern int rhetor_count;

/* Symbol page 20 (PS emission page 12). */
extern int temples_count;
extern int no_of_trading_posts;
extern int arena_culture_count;
extern int circus_culture_pass_count;
extern int circus_maximus_culture_count;
extern int no_of_workcamps;
extern int arena_culture_pass_count;
extern int market_count;
extern int circus_maximus_culture_pass_count;
extern int colosseum_culture_pass_count;
extern int business_pass_count;
extern int no_of_ports;
extern int plaza_culture_pass_count;
extern int region_pass_count;
extern int region_running_count;
extern int robbery_count;
extern int circus_culture_count;
extern int market_pass_count;
extern int plaza_culture_count;
extern int gardens_culture_count;
extern int colosseum_culture_count;
extern int business_count;
extern int gardens_culture_pass_count;
extern int no_of_warehouses;
extern int no_of_shipyards;

/* Symbol page 21 (PS emission page 11). */
extern int no_of_connected_towns;
extern int attacking_region;
extern int plague_accident;
extern int no_of_towns;
extern unsigned char empire_connections[];
extern int no_of_farms;
extern int region_accident;
extern int road_cover;
extern int road_rate;
extern int region_rate;
extern int no_of_villages;
extern int no_of_empire_connections;
extern int revolt_accident;
extern int no_of_border_towns;
extern int fire_accident;
extern int no_of_mines;
extern int water_trouble_rate;
extern int wall_accident;
extern int road_accident;
extern int fire_cover;
extern int attack_direction;
extern int attack_from_sea;
extern int fire_rate;
extern int wall_rate;
extern int no_of_quarrys;

/* Symbol page 22 (PS emission page 10). */
extern int water_cover;
extern int wall_cover;
extern int q_ptr;
extern unsigned char q_rhetor;
extern unsigned char q_business;
extern unsigned char q_grammaticus;
extern unsigned char q_market;
extern unsigned char q_baths;
extern unsigned char q_type;
extern unsigned char q_aqua;
extern unsigned char q_sub_aqua;
extern unsigned char q_barracks;
extern unsigned char q_colosseum;
extern unsigned char q_theatre;
extern unsigned char q_circus;
extern unsigned char q_cover2;
extern unsigned char q_cover1;
extern unsigned char q_entertainment;
extern unsigned char q_admin;
extern unsigned char q_flag;
extern unsigned char q_wall;
extern unsigned char q_supply;
extern unsigned char q_gfx;
extern unsigned char q_range3;
extern unsigned char q_range1;

/* Symbol page 23 (PS emission page 9). */
extern int q_local;
extern int q_workhouse;
extern int q_no_of_people;
extern int q_supplies;
extern int q_hospital_access;
extern short enemy_army;
extern unsigned char q_had_goods;
extern unsigned char q_ind_pop;
extern unsigned char q_gate;
extern unsigned char q_ind_market;
extern unsigned char q_security;
extern unsigned char q_business_low;
extern unsigned char q_wh_level;
extern unsigned char q_shell;
extern unsigned char q_business_vlow;
extern unsigned char q_occa;
extern unsigned char q_ind_output;
extern signed char q_lv;
extern unsigned char q_near_market;
extern unsigned char q_goods;
extern unsigned char q_outside;
extern unsigned char q_road_access;
extern unsigned char q_road;
extern unsigned char q_prefecture;
extern unsigned char q_patrol;

/* Symbol page 24 (PS emission page 8). */
extern int evolve_row;
extern int no_of_citizens;
extern int plague_spread_count;
extern int library_cover;
extern int no_of_rioters;
extern int shell_last_value;
extern int no_of_barbarians;
extern int shell_push_direction;
extern int no_of_arrows;
extern int no_of_figures;
extern int plague_spread_target;
extern int no_of_units;
extern int plague_spread_direction;
extern int shell_wall_flag;
extern int evolve_tick4;
extern int fire_spread_target;
extern int no_of_armies;
extern int evolve_tick3;
extern int evolve_clock;
extern int q_pop_level;
extern int fire_spread_count;
extern int evolve_count;
extern int fire_spread_direction;
extern int evolve_col;
extern int hospital_cover;

/* Symbol page 25 (PS emission page 7). */
extern int top_lv_spot;
extern int east_border_y;
extern int east_border_x;
extern int reg_city_ptr;
extern int west_trader_is;
extern int x;
extern int y;
extern int south_trader_is;
extern int east_trader_is;
extern int north_trader_count0;
extern int west_border_y;
extern int west_border_x;
extern int top_lv_y;
extern int top_lv_x;
extern int top_lv_ptr;
extern int north_trader_is;
extern int top_lv;
extern int south_trader_count0;
extern int north_border_x;
extern int north_border_y;
extern int south_border_x;
extern int south_border_y;
extern int reg_city_x;
extern int reg_city_y;
extern int east_trader_count0;

/* Symbol page 26 (PS emission page 6). */
extern int history_start_ptr;
extern int west_trader_count1;
extern int west_trader_count0;
extern int east_trader_brings;
extern int completed_provinces;
extern struct hut_rec hut_list[];
extern int west_trader_brings;
extern int history_entries;
extern int current_gdp;
extern int history_entry[];
extern int auto_conquered_months;
extern int province_difficulty;
extern int province_is;
extern int north_trader_count1;
extern int provinces_on_offer;
extern int rolling_profit;
extern int history_graph_length;
extern int north_trader_brings;
extern int south_trader_count1;
extern int auto_conquered;
extern int east_trader_count1;
extern int history_end_ptr;
extern int south_trader_brings;
extern unsigned char first_choice;
extern unsigned char choice_info;

/* Symbol page 27 (PS emission page 5). */
extern int culture_rating;
extern int empire_rating;
extern int housing_cheat;
extern int pax_romanum;
extern int prosperity_rating;
extern int refused_promotion;
extern int peace_rating_pop_limit;
extern int z_x;
extern int z_y;
extern int utility_level;
extern int average_rating;
extern int culture_rating_pop_limit;
extern int current_temple_tip;
extern int z_ptr;
extern int empire_rating_pop_limit;
extern int zone_x;
extern int zone_y;
extern int promotion_cheat;
extern int religion_level;
extern int player_rank;
extern int peace_rating;
extern int prosperity_rating_pop_limit;
extern int entertainment_level;
extern unsigned short int_battle_header[];
extern unsigned char choice_count;

/* Symbol page 28 (PS emission page 4). */
extern int gmn_max_run;
extern int gmn_ew_count;
extern int gmn_err_x;
extern int gmn_err_y;
extern int gmn_polar_count;
extern int gmn_flag;
extern int coast_count;
extern int gmn_type_limit;
extern int gmn_y;
extern int gmn_x;
extern int gmn_err_sptr;
extern int gmn_run;
extern int gmn_nesw_count;
extern int gmn_count;
extern int gmn_sptr;
extern int gmn_ns_count;
extern int gmn_density;
extern int gmn_type;
extern int gmn_nwse_count;
extern int ofset_y;
extern int ofset_x;
extern unsigned char forum_dept_over;
extern char ov2_map_mode;
extern signed char stone_random_count;
extern unsigned char forum_dept;

/* Symbol page 29 (PS emission page 3). */
extern int health_debar;
extern int icon_strip_toggle;
extern int last_icon_used;
extern int selected_icon_text;
extern int unrest_debar;
extern int selection_is;
extern int selected_icon_no;
extern int industry_debar;
extern int admin_debar;
extern int update_ov_bar;
extern int security_debar;
extern int lv_debar;
extern int arena_top_count;
extern int last_icon_over;
extern int unrest_random_count;
extern int entertainment_debar;
extern int education_debar;
extern int water_debar;
extern short hunting_army;
extern short unit_a;
extern short their_battle_army;
extern short our_battle_army;
extern unsigned char last_forum_dept;
extern char need_glf;
extern unsigned char ov_map_mode;

/* Symbol page 30 (PS emission page 2). */
extern int reg_placing_type;
extern int placing_cost;
extern int total_build_cost;
extern int business_build_type;
extern int particles_built;
extern int placing_flags;
extern int starting_denarii;
extern int industry_build_type;
extern int industry_build_on;
extern int illegal_build;
extern int industry_build_ok;
extern int nof_hot_spots;
extern int first_help_page;
extern int flag_for_workhouse_request;
extern int this_help_page;
extern int particles_cleared;
extern int over_an_army;
extern int reg_placing_flags;
extern int colosseum_top_count;
extern int query_mode;
extern int last_house_query_mode;
extern int placing_type;
extern int this_help_action;
extern short tracking_army;
extern short figure_a;

/* Symbol page 31 (PS emission page 1). */
extern unsigned char * figure5_data;
extern unsigned char * tops_data;
extern unsigned char * building_data4;
extern unsigned char * building_data2;
extern unsigned char * building_data3;
extern unsigned char * figure6_data;
extern unsigned char * building_data1;
extern int query_panel_reduction;
extern unsigned char * house_data;
extern int test_result4;
extern int barbarian_name_count;
extern int test_result3;
extern int test_result2;
extern int test_result1;
extern int queried_person;
extern int exit_y_at;
extern int exit_x_at;
extern unsigned char * people_data;
extern unsigned char * figure1_data;
extern unsigned char * fixt_data;
extern unsigned char * figure2_data;
extern int nof_query_buttons;
extern unsigned char * figure3_data;
extern unsigned char * figure4_data;
extern int roman_name_count;

/* Symbol page 32 (PS emission page 0). */
extern unsigned char * figure7_data;
extern int x1;
extern unsigned char * figure8_data;
extern unsigned char * figure9_data;
extern unsigned char * figure10_data;
extern short temp_arrow;
extern short enemy_figure;
extern short enemy_unit;
extern short temp_unit;
extern short army_b;
extern short army_a;

#endif /* C2_VARS_H */
