
#include "c2_vars.h"
#include "c2_types.h"
#include "c2_data.h"

struct byte_delta_rec gmn_ofsets[8] = {
    { 0, -1 },
    { 1, -1 },
    { 1, 0 },
    { 1, 1 },
    { 0, 1 },
    { -1, 1 },
    { -1, 0 },
    { -1, -1 }
};

int steves_security_real[7] = { 538976288, 2021138464, 2021161080, 2021161080, 1482184792, 538990680, 538976288 };

unsigned short int_battle_header[232];
unsigned char landfill[5440];
unsigned short int_city_header[232];
unsigned short int_region_header[232];
unsigned char misc[3584];
struct help_hotspot help_page_hot_spots[20];
short help_history[200];
int gmn_types[2];
char gmn[16];
struct province_industry province_industries[8];
struct industry_rec industry[16];
struct slave_req slave_requirements[8];
int danger_flag_list[20];
int city_flag_list[20];
int prov_flag_list[20];
struct msg_slot message_list[16];
char region_palette[768];
char city_palette[768];
struct figure_rec figure_list[201];
int empire_won[50];
unsigned char landfill_pool[6400];
struct region_cell region_map[REGION_W * REGION_H];
struct battle_cell battle_map[BATTLE_W * BATTLE_H];
struct city_cell city_map[CITY_W * CITY_H];
unsigned char * figure7_data;
int x1;
unsigned char * figure8_data;
unsigned char * figure9_data;
unsigned char * figure10_data;
unsigned char * figure5_data;
unsigned char * tops_data;
unsigned char * building_data4;
unsigned char * building_data2;
unsigned char * building_data3;
unsigned char * figure6_data;
unsigned char * building_data1;
int query_panel_reduction;
unsigned char * house_data;
int barbarian_name_count;
int test_result4;
int test_result3;
int test_result2;
int test_result1;
int queried_person;
int exit_y_at;
int exit_x_at;
unsigned char * people_data;
unsigned char * figure1_data;
unsigned char * fixt_data;
unsigned char * figure2_data;
int nof_query_buttons;
unsigned char * figure3_data;
unsigned char * figure4_data;
int roman_name_count;
int reg_placing_type;
int placing_cost;
int total_build_cost;
int business_build_type;
int particles_built;
int placing_flags;
int starting_denarii;
int industry_build_type;
int industry_build_on;
int illegal_build;
int industry_build_ok;
int nof_hot_spots;
int first_help_page;
int this_help_page;
int flag_for_workhouse_request;
int particles_cleared;
int over_an_army;
int reg_placing_flags;
int colosseum_top_count;
int last_house_query_mode;
int query_mode;
int placing_type;
int this_help_action;
int health_debar;
int icon_strip_toggle;
int last_icon_used;
int selected_icon_text;
int unrest_debar;
int selection_is;
int selected_icon_no;
int industry_debar;
int admin_debar;
int update_ov_bar;
int security_debar;
int lv_debar;
int arena_top_count;
int last_icon_over;
int unrest_random_count;
int entertainment_debar;
int education_debar;
int water_debar;
int gmn_max_run;
int gmn_ew_count;
int gmn_err_x;
int gmn_err_y;
int gmn_polar_count;
int gmn_flag;
int coast_count;
int gmn_type_limit;
int gmn_y;
int gmn_err_sptr;
int gmn_x;
int gmn_run;
int gmn_nesw_count;
int gmn_count;
int gmn_sptr;
int gmn_ns_count;
int gmn_type;
int gmn_density;
int gmn_nwse_count;
int ofset_y;
int ofset_x;
int culture_rating;
int empire_rating;
int housing_cheat;
int pax_romanum;
int prosperity_rating;
int refused_promotion;
int peace_rating_pop_limit;
int z_x;
int z_y;
int utility_level;
int culture_rating_pop_limit;
int average_rating;
int current_temple_tip;
int z_ptr;
int zone_x;
int empire_rating_pop_limit;
int zone_y;
int religion_level;
int promotion_cheat;
int peace_rating;
int player_rank;
int prosperity_rating_pop_limit;
int entertainment_level;
int history_start_ptr;
int west_trader_count1;
int west_trader_count0;
int east_trader_brings;
int completed_provinces;
struct hut_rec hut_list[4];
int west_trader_brings;
int history_entries;
int current_gdp;
int history_entry[5];
int auto_conquered_months;
int province_difficulty;
int province_is;
int north_trader_count1;
int provinces_on_offer;
int rolling_profit;
int history_graph_length;
int north_trader_brings;
int south_trader_count1;
int auto_conquered;
int east_trader_count1;
int history_end_ptr;
int south_trader_brings;
int top_lv_spot;
int east_border_y;
int east_border_x;
int reg_city_ptr;
int west_trader_is;
int x;
int y;
int south_trader_is;
int east_trader_is;
int north_trader_count0;
int west_border_y;
int west_border_x;
int top_lv_y;
int top_lv_x;
int top_lv_ptr;
int north_trader_is;
int top_lv;
int south_trader_count0;
int north_border_x;
int north_border_y;
int south_border_x;
int south_border_y;
int reg_city_x;
int east_trader_count0;
int reg_city_y;
int evolve_row;
int plague_spread_count;
int no_of_citizens;
int library_cover;
int no_of_rioters;
int shell_last_value;
int no_of_barbarians;
int shell_push_direction;
int no_of_arrows;
int no_of_figures;
int plague_spread_target;
int no_of_units;
int plague_spread_direction;
int shell_wall_flag;
int evolve_tick4;
int fire_spread_target;
int no_of_armies;
int evolve_tick3;
int evolve_clock;
int q_pop_level;
int fire_spread_count;
int evolve_count;
int fire_spread_direction;
int evolve_col;
int hospital_cover;
int q_local;
int q_workhouse;
int q_no_of_people;
int q_supplies;
int q_hospital_access;
int water_cover;
int wall_cover;
int q_ptr;
int no_of_connected_towns;
int attacking_region;
int plague_accident;
int no_of_towns;
unsigned char empire_connections[4];
int no_of_farms;
int region_accident;
int road_cover;
int region_rate;
int road_rate;
int no_of_villages;
int revolt_accident;
int no_of_empire_connections;
int no_of_border_towns;
int fire_accident;
int no_of_mines;
int water_trouble_rate;
int wall_accident;
int road_accident;
int fire_cover;
int attack_direction;
int fire_rate;
int attack_from_sea;
int wall_rate;
int no_of_quarrys;
int temples_count;
int no_of_trading_posts;
int arena_culture_count;
int circus_culture_pass_count;
int no_of_workcamps;
int circus_maximus_culture_count;
int arena_culture_pass_count;
int market_count;
int circus_maximus_culture_pass_count;
int colosseum_culture_pass_count;
int business_pass_count;
int no_of_ports;
int plaza_culture_pass_count;
int region_pass_count;
int region_running_count;
int robbery_count;
int circus_culture_count;
int market_pass_count;
int plaza_culture_count;
int gardens_culture_count;
int colosseum_culture_count;
int business_count;
int gardens_culture_pass_count;
int no_of_warehouses;
int no_of_shipyards;
int accessed_libraries_count;
int rhetor_pass_count;
int grammaticus_culture_pass_count;
int arena_count;
int theatre_pass_count;
int odium_pass_count;
int circus_maximus_pass_count;
int colosseum_pass_count;
int grammaticus_count;
int circus_maximus_count;
int odium_count;
int grammaticus_culture_count;
int grammaticus_pass_count;
int odium_culture_count;
int arena_pass_count;
int circus_pass_count;
int theatre_culture_pass_count;
int rhetor_culture_count;
int theatre_count;
int theatre_culture_count;
int odium_culture_pass_count;
int circus_count;
int colosseum_count;
int rhetor_culture_pass_count;
int rhetor_count;
int med_temples_culture_count;
int med_robbery_pass_count;
int med_temples_culture_pass_count;
int small_temples_culture_pass_count;
int libraries_count;
int large_robbery_count;
int med_robbery_count;
int large_temples_pass_count;
int hospitals_count;
int libraries_pass_count;
int small_robbery_pass_count;
int large_robbery_pass_count;
int large_temples_culture_pass_count;
int med_temples_pass_count;
int small_temples_culture_count;
int large_temples_culture_count;
int small_temples_count;
int accessed_hospitals_count;
int small_temples_pass_count;
int accessed_hospitals_pass_count;
int small_robbery_count;
int med_temples_count;
int hospitals_pass_count;
int accessed_libraries_pass_count;
int large_temples_count;
int fountains_count;
int fountains_pass_count;
int forts_count;
int large_forums_pass_count;
int supplied_baths_count;
int barracks_pass_count;
int prefectures_count;
int supplied_fountains_count;
int supplied_fountains_pass_count;
int medium_forums_pass_count;
int large_forums_count;
int supplied_baths_pass_count;
int small_forums_count;
int structure_running_count;
int baths_count;
int road_running_count;
int fire_running_count;
int plague_running_count;
int baths_pass_count;
int prefectures_pass_count;
int medium_forums_count;
int forts_pass_count;
int water_running_count;
int barracks_count;
int small_forums_pass_count;
int average_cohort_morale;
int current_no_of_specials;
int lacking_specials;
int pop_tax_counts;
int population_running_count;
int pop_income_pass_count;
int road_pass_count;
int ind_tax_counts;
int no_of_census_passes;
int population_pass_count;
int plague_pass_count;
int ind_tax_last_count;
int ind_tax_running_total;
int last_adjusted_cohort;
int employment_pass_count;
int extra_specials;
int pop_tax_last_count;
int fire_pass_count;
int structure_pass_count;
int pop_tax_running_total;
int needed_no_of_specials;
int total_no_of_specials;
int employment_running_count;
int ind_income_pass_count;
int average_cohort_readiness;
int current_no_of_auxillaries;
int army_wage_level;
int total_no_of_soldiers;
int total_no_of_irregulars;
int current_no_of_regulars;
int current_no_of_soldiers;
int needed_no_of_centuries;
int needed_no_of_auxillaries;
int conscription_rate;
int current_no_of_irregulars;
int needed_no_of_soldiers;
int needed_no_of_regulars;
int total_no_of_centuries;
int extra_irregulars;
int lacking_auxillaries;
int extra_auxillaries;
int total_no_of_regulars;
int total_no_of_auxillaries;
int total_no_of_cohorts;
int no_of_army_buttons;
int current_no_of_centuries;
int needed_no_of_irregulars;
int lacking_regulars;
int extra_regulars;
int lacking_irregulars;
int average_ind_tax_asses;
int last_tribute;
int moving_tribute;
int last_years_denarii;
int average_ind_tax_denariis;
int this_years_pop_tax;
int estimate_tribute;
int average_pop_tax_denariis;
int imperial_send_amount;
int last_years_ind_tax;
int forum_viewed_army;
int this_years_population;
int average_pop_tax_asses;
int tribute;
int income_multiple;
int total_amount_of_bribes;
int last_years_pop_tax;
int total_no_of_bribes;
int imperial_gift_level;
int last_years_population;
int imperial_req_amount;
int this_years_denarii;
int av_imperial_gift_level;
int account_tribute;
int this_years_ind_tax;
int players_denarii;
int imperial_req_goods;
int last_imperial_tax_percent;
int estimate_ind_tax;
int stolen_denarii;
int donation_level;
int estimate_total;
int last_imperial_tax_amount;
int total_imperial_taxes;
int estimate_operating_cost;
int current_construction_cost;
int account_operating_cost;
int account_ind_tax;
int imperial_tax;
int imperial_review;
int estimate_construction_cost;
int estimate_pop_tax;
int players_salary;
int imperial_favour;
int slave_random;
int account_construction_cost;
int imperial_request;
int account_pop_tax;
int current_operating_cost;
int account_total;
int slaves;
int months_to_game_over;
int months_since_last_revolt;
int week;
int months_since_last_city_attack;
int pop_tax_rate;
int employment_rate;
int slave_population_change;
int month;
int employees;
int months_since_last_horde;
int max_population;
int slave_welfare_bill;
int years_elapsed;
int year;
int game_state;
int ind_tax_rate;
int denarii;
int population;
int start_year;
int slave_population_final_estimate;
int months_since_last_raider;
int years_elapsed_in_region;
int slave_population_estimate;
int months_since_last_war;
int insurrection_future;
int elastic_start_dirc;
int pop_growth_factor;
int over_y;
int over_x;
int ind_growth_future;
int action_sound;
int best_elastic_value;
int over_ptr;
int insurrection_factor;
int last_army_route_point;
int pop_growth_extra_count;
int act_start_ptr;
int act_start_x;
int act_start_y;
int ind_growth_factor;
int pop_growth_extra;
int had_clear_sound;
int pop_growth_future;
int this_route_number;
int best_elastic_dirc;
int act_start_pm_ptr;
int no_of_city_flags;
int last_danger_flag;
int flag_mode;
int danger_flag_map_mode;
int pm_over_cm_ptr;
int no_of_danger_flags;
int last_city_flag;
int last_prov_flag;
int flag_mode_decay_count;
int old_pm_over;
int city_pm_y;
int city_pm_x;
int com_h;
int com_w;
int com_x;
int com_y;
int pm_over;
int no_of_prov_flags;
int battle_pm_y;
int battle_pm_x;
int region_pm_x;
int region_pm_y;
int pm_screen_x_end;
int pm_screen_width;
int pm_build_shape;
int pm_y_clip;
int pm_screen_y_start;
int pm_screen_x_start;
int pm_shown_y;
int pm_y_edge;
int pm_shown_x;
int pm_y;
int pm_x;
int cm_x;
int pm_x_coord;
int cm_y;
int pm_y_coord;
int pm_x_edge;
int pm_diamond_width;
int pm_diamond_half_width;
int pm_screen_height;
int pm_diamond_height;
int pm_shown_ptr;
int pm_over_y;
int pm_over_x;
int pm_diamond_half_height;
int pm_screen_y_end;
int map_direction;
int overlays_on;
int map_height_reduction;
int map_actual_atom;
int city_rotation;
int start_y_pos;
int prov_zoom_level;
int city_ptr;
int cm_dptr;
int map_actual_width;
int start_x_pos;
int cm_sptr;
int map_width_reduction;
int prov_rotation;
unsigned char * city_qptr;
int city_zoom_level;
int map_actual_height;
int scroll_amount;
int in_the_forum;
int start_sptr;
int demo_mode;
int update_icon;
int tutorial_page;
int warned_new_struct;
int battle_direction;
int city_direction;
int region_direction;
int final_bribe;
int slave_warning;
int tutorial_mode;
int in_census_mode;
int warned_city_size;
int last_city_mood;
int bad_mood;
int tune_mood_hold;
int new_structure_is;
int city_tune_playing;
int message_goto_ptr;
int tune_branch;
int warned_of_not_build;
int last_battle_mood;
int tune_branch_count;
int free_message_ptr;
int show_message_ptr;
int tune_mood;
int marching_fx;
int odd_battle_tune;
int hlite_off_y;
int hlite_off_x;
int blue_cycle_count;
int hlite_squares;
int bat_enemy_right_flank_unit;
int bat_enemy_second_fan_unit;
int emergency_mood;
int hlite_left;
int hlite_centre_y;
int hlite_centre_x;
int nomansland_ptr;
int hlite_right;
int hlite_top;
int battle_drag_start_y;
int battle_drag_start_x;
int next_cohort_free;
int no_of_cohorts_in_action;
int bat_enemy_first_fan_unit;
int hlite_off_ptr;
int hlite_bottom;
int bat_enemy_left_flank_unit;
int threat_mood;
int roman_right_edge;
int mercs_in_army;
int battle2_ptr;
int mercs_tribe;
int battle_drag_on;
int mercs_cost_per_50;
int max_mercs_allowed;
int roman_left_edge;
int their_battle_irregs;
int mercs_missile;
int target_unit_debar;
int return_map_mode;
int mercs_from;
int mercs_type;
int roman_front_edge;
int battle_turbo;
int their_battle_auxs;
int battle_turbo_count;
int roman_back_edge;
int return_zoom_level;
int mercs_speed;
int mercs_catagory;
int battle_type;
int their_battle_regs;
int their_battle_horse;
int our_battle_specials;
int our_battle_units;
int battle_stats_morale;
int our_battle_routs;
int their_battle_stance;
int their_battle_start_men;
int their_battle_men;
int our_battle_start_men;
int our_battle_morale;
int battle_stats_nof_units;
int battle_stats_type;
int retreat_flag;
int battle_stats_men;
int their_battle_morale;
int our_battle_horse;
int their_battle_routs;
int our_battle_stance;
int their_battle_specials;
int our_battle_auxs;
int battle_stats_control;
int our_battle_irregs;
int our_battle_regs;
int battle_npc_retreat_count;
int their_battle_units;
int battle_stats_start_men;
int battle_over_count;
int battle_scale;
int bat_tribe;
int battle_ai_count;
int our_battle_men;
int battle_victor;
int battle_state;
int battle_setup_count;
int ferret_run_length;
int region_over;
struct army_route_rec army_routes[10];
signed char fire_zones[100];
int pseudo_map[PM_H][PM_W];
unsigned char q_people_list[10];
char cohort_in_action[10];
struct citizen_rec citizen_list[201];
unsigned char empire[50];
struct unit_rec unit_list[51];
char ferret_run[22];
struct army_rec army_list[26];
short temp_arrow;
short enemy_figure;
short enemy_unit;
short temp_unit;
short army_b;
short army_a;
short tracking_army;
short figure_a;
short hunting_army;
short unit_a;
short their_battle_army;
short our_battle_army;
short enemy_army;
short enemy_citizen;
short citizen_b;
short citizen_a;
short arrow_a;
short created_unit_no;
short unit_no;
short arrow_no;
short temp_figure;
short figure_no;
short created_citizen_no;
short temp_citizen;
short created_figure_no;
short citizen_no;
short created_arrow_no;
short created_army_no;
short temp_army;
short army_no;
struct arrow_rec arrow_list[201];
unsigned char last_forum_dept;
char need_glf;
unsigned char ov_map_mode;
unsigned char forum_dept_over;
char ov2_map_mode;
signed char stone_random_count;
unsigned char forum_dept;
unsigned char choice_count;
unsigned char first_choice;
unsigned char choice_info;
unsigned char q_had_goods;
unsigned char q_ind_pop;
unsigned char q_gate;
unsigned char q_ind_market;
unsigned char q_security;
unsigned char q_business_low;
unsigned char q_wh_level;
unsigned char q_shell;
unsigned char q_occa;
unsigned char q_business_vlow;
unsigned char q_ind_output;
signed char q_lv;
unsigned char q_near_market;
unsigned char q_goods;
unsigned char q_outside;
unsigned char q_road_access;
unsigned char q_road;
unsigned char q_prefecture;
unsigned char q_patrol;
unsigned char q_rhetor;
unsigned char q_business;
unsigned char q_grammaticus;
unsigned char q_market;
unsigned char q_baths;
unsigned char q_type;
unsigned char q_aqua;
unsigned char q_sub_aqua;
unsigned char q_barracks;
unsigned char q_colosseum;
unsigned char q_circus;
unsigned char q_theatre;
unsigned char q_cover2;
unsigned char q_cover1;
unsigned char q_entertainment;
unsigned char q_admin;
unsigned char q_flag;
unsigned char q_wall;
unsigned char q_supply;
unsigned char q_gfx;
unsigned char q_range3;
unsigned char q_range1;
unsigned char w_dirc;
unsigned char fig_at_edge;
unsigned char zoom_level;
unsigned char scrolling;
unsigned char map_mode;
unsigned char update_map;
unsigned char zoom_in_decay_count;
char old_zoom_level;
unsigned char old_scrolling;
unsigned char sb_rm_undo_flushed;
unsigned char sb_cm_undo_flushed;
unsigned char update_landfill;
unsigned char redraw_icons;
unsigned char gen_refresh1;
unsigned char gen_refresh3;
unsigned char gen_refresh2;
unsigned char stopped_scrolling;
char gen_refresh4;
char old_map_mode;
unsigned char redraw_topline;
unsigned char warned_of_emperor_reply_level;
char warned_of_free4;
char warned_of_free5;
char warned_of_fire;
unsigned char warned_of_robbery;
unsigned char warned_of_emperor_reply_month;
unsigned char put_a_message;
unsigned char warned_of_emperor;
char warned_of_cutbacks;
